// src/constants/slogans.js

export const SLOGAN_SETS = {
  "3PM": [
    { id: "3pm-001", groupKey: "3PM", text: "The 3PMers: Because chaos has office hours." },
    { id: "3pm-002", groupKey: "3PM", text: "We recover loudly at 3PM so we don't relapse quietly at 3AM." },
    { id: "3pm-003", groupKey: "3PM", text: "The 3PMers: Procrastinating self-destruction since... today." },
    { id: "3pm-004", groupKey: "3PM", text: "If it's 3PM, we're either healing or lying about it." },
    { id: "3pm-005", groupKey: "3PM", text: "At 3PM we don't rise and grind. We wake, panic, then recover." },
    { id: "3pm-006", groupKey: "3PM", text: "3PM: When sanity clocks in and denial clocks out." },
    { id: "3pm-007", groupKey: "3PM", text: "We didn't choose 3PM. 3PM chose our nervous systems." },
    { id: "3pm-008", groupKey: "3PM", text: "The 3PMers: Hope, caffeine, and trauma bonding." },
    { id: "3pm-009", groupKey: "3PM", text: "3PM is where emotional damage meets calendar discipline." },
    { id: "3pm-010", groupKey: "3PM", text: "At 3PM, miracles are legally obligated to happen." },
    { id: "3pm-011", groupKey: "3PM", text: "At 3PM, clean isn't our personality, but it's a good placeholder." },
    { id: "3pm-012", groupKey: "3PM", text: "Our group has one rule: don't relapse before 3PM." },
    { id: "3pm-013", groupKey: "3PM", text: "We don't hit rock bottom anymore — we penciled it in for 3PM and came here instead." },
    { id: "3pm-014", groupKey: "3PM", text: "The 3PMers: We've survived worse Zoom calls." },
    { id: "3pm-015", groupKey: "3PM", text: "3PM recovery, but make it existential." },
    { id: "3pm-016", groupKey: "3PM", text: "We don't do mornings. We do 3PM." },
    { id: "3pm-017", groupKey: "3PM", text: "3PM healing is cheaper than cocaine. Still expensive emotionally." },
    { id: "3pm-018", groupKey: "3PM", text: "The 3PMers: Turning emotional chaos into plot twists." },
    { id: "3pm-019", groupKey: "3PM", text: "We don't trust mornings or feelings, but we trust 3PM." },
    { id: "3pm-020", groupKey: "3PM", text: "Addiction came for our souls. 3PM negotiated visitation rights." },
    { id: "3pm-021", groupKey: "3PM", text: "The 3PMers: Miracles taste like awkward honesty." },
    { id: "3pm-022", groupKey: "3PM", text: "At 3PM we don't take ourselves seriously — just our sobriety." },
    { id: "3pm-023", groupKey: "3PM", text: "3PM: Where sarcasm meets spiritual awakening." },
    { id: "3pm-024", groupKey: "3PM", text: "3PM: The hour where shame gets benched." },
    { id: "3pm-025", groupKey: "3PM", text: "The 3PMers: Not dead. Not High. Not sure what the hell we're doing — but we're here." },
    { id: "3pm-026", groupKey: "3PM", text: "3PM: Because noon was too early to be this honest." },
    { id: "3pm-027", groupKey: "3PM", text: "The 3PMers: Afternoon chaos, evening serenity (hopefully)." },
    { id: "3pm-028", groupKey: "3PM", text: "If it's 2:59 PM, we're almost emotionally available." },
    { id: "3pm-029", groupKey: "3PM", text: "3PM: The only time of day we voluntarily answer 'How are you?'." },
    { id: "3pm-030", groupKey: "3PM", text: "The 3PMers: Proof that nothing good happens after midnight, but a lot happens at 3PM." },
    { id: "3pm-031", groupKey: "3PM", text: "3PM is when our feelings clock in and our excuses clock out." },
    { id: "3pm-032", groupKey: "3PM", text: "Some people take coffee breaks. We take 3PM reality breaks." },
    { id: "3pm-033", groupKey: "3PM", text: "3PM: Scheduled maintenance for spiritually glitchy humans." },
    { id: "3pm-034", groupKey: "3PM", text: "The 3PMers: Turning 'just for today' into 'see you tomorrow at 3PM'." },
    { id: "3pm-035", groupKey: "3PM", text: "At 3PM, we're not fine, but we're here." },
    { id: "3pm-036", groupKey: "3PM", text: "3PM: Daily reminder that we made it through the dangerous part of the day sober." },
    { id: "3pm-037", groupKey: "3PM", text: "The 3PMers: Afternoon meeting, lifetime side effects." },
    { id: "3pm-038", groupKey: "3PM", text: "3PM is the alarm clock for our denial." },
    { id: "3pm-039", groupKey: "3PM", text: "At 3PM, we stop doomscrolling and start step-working." },
    { id: "3pm-040", groupKey: "3PM", text: "3PM: The most honest hour in our calendar." },
    { id: "3pm-041", groupKey: "3PM", text: "The 3PMers: Because healing before lunch feels illegal." },
    { id: "3pm-042", groupKey: "3PM", text: "3PM: Where accountability meets caffeine withdrawal." },
    { id: "3pm-043", groupKey: "3PM", text: "The 3PMers: Afternoons are for honesty, not hallucinations." },
    { id: "3pm-044", groupKey: "3PM", text: "3PM: Proof that the universe gives second chances after nap time." },
    { id: "3pm-045", groupKey: "3PM", text: "The 3PMers: Our serenity starts after noon and ends whenever feelings do." },
    { id: "3pm-046", groupKey: "3PM", text: "3PM is the only hour where confessing insanity sounds normal." },
    { id: "3pm-047", groupKey: "3PM", text: "If it's 3PM, someone is oversharing and someone else needed to hear it." },
    { id: "3pm-048", groupKey: "3PM", text: "3PM: The hour we stop negotiating with our addiction's HR department." },
    { id: "3pm-049", groupKey: "3PM", text: "The 3PMers: Emotionally unstable, spiritually available." },
    { id: "3pm-050", groupKey: "3PM", text: "3PM: Our Higher Power knows we don’t wake up before noon." },
    { id: "3pm-051", groupKey: "3PM", text: "At 3PM we don't heal — we recalibrate and hope for the best." },
    { id: "3pm-052", groupKey: "3PM", text: "3PM: Sponsored by caffeine, emotional damage, and questionable life choices." },
    { id: "3pm-053", groupKey: "3PM", text: "The 3PMers: Your last safe stop before 4PM anxiety attacks." },
    { id: "3pm-054", groupKey: "3PM", text: "3PM: The hour we realize feelings aren't fatal. Just inconvenient." },
    { id: "3pm-055", groupKey: "3PM", text: "At 3PM, vulnerability and sarcasm share a chair." },
    { id: "3pm-056", groupKey: "3PM", text: "3PM: Half recovery meeting, half existential performance art." },
    { id: "3pm-057", groupKey: "3PM", text: "The 3PMers: Where we scream internally but share externally." },
    { id: "3pm-058", groupKey: "3PM", text: "3PM: The most spiritual thing we do before dinner." },
    { id: "3pm-059", groupKey: "3PM", text: "The 3PMers: Because emotional regulation is easier after snacks." },
    { id: "3pm-060", groupKey: "3PM", text: "3PM: The hour that saved our lives more times than logic ever did." },
    { id: "3pm-061", groupKey: "3PM", text: "At 3PM, we tell on our addiction before it tells on us." },
    { id: "3pm-062", groupKey: "3PM", text: "The 3PMers: Our superpower is showing up even when we don't want to." },
    { id: "3pm-063", groupKey: "3PM", text: "3PM: If the feelings don’t leave, neither do we." },
    { id: "3pm-064", groupKey: "3PM", text: "3PM: Where hope clocked in even when we didn't." },
    { id: "3pm-065", groupKey: "3PM", text: "The 3PMers: Where every chair has trauma and every trauma has a chair." },
    { id: "3pm-066", groupKey: "3PM", text: "3PM: If we’re not recovering, we’re at least not using." },
    { id: "3pm-067", groupKey: "3PM", text: "The 3PMers: We meet halfway between despair and dinner." },
    { id: "3pm-068", groupKey: "3PM", text: "The 3PMers: Emotional support, but make it punctual." },
    { id: "3pm-069", groupKey: "3PM", text: "3PM: The daily reminder that we survived morning chaos." },
    { id: "3pm-070", groupKey: "3PM", text: "The 3PMers: Because healing at 9AM was never going to happen." },
    { id: "3pm-071", groupKey: "3PM", text: "3PM: Where denial takes a smoke break." },
    { id: "3pm-072", groupKey: "3PM", text: "The 3PMers: We don’t share trauma — we repurpose it." },
    { id: "3pm-073", groupKey: "3PM", text: "3PM: The only hour our addiction can’t schedule a comeback." },
    { id: "3pm-074", groupKey: "3PM", text: "Warning: It's almost 3PM. Feelings are approaching." },
    { id: "3pm-075", groupKey: "3PM", text: "3PM alert: Prepare to explain your life choices out loud." },
    { id: "3pm-076", groupKey: "3PM", text: "Reminder: At 3PM, excuses expire without notice." },
    { id: "3pm-077", groupKey: "3PM", text: "3PM detected. Your denial is almost out of warranty." },
    { id: "3pm-078", groupKey: "3PM", text: "Incoming 3PM. Please silence your ego." },
    { id: "3pm-079", groupKey: "3PM", text: "Heads up: It’s nearly 3PM. Emotional nudity required." },
    { id: "3pm-080", groupKey: "3PM", text: "Approaching 3PM. Panic responsibly." },
    { id: "3pm-081", groupKey: "3PM", text: "3PM warning: Lies lose structural integrity in 5 minutes." },
    { id: "3pm-082", groupKey: "3PM", text: "Brace yourself. 3PM is where honesty happens by accident." },
    { id: "3pm-083", groupKey: "3PM", text: "3PM is imminent. Stretch your coping mechanisms." },
    { id: "3pm-084", groupKey: "3PM", text: "Attention: 3PM is not a drill. Feelings may occur." },
    { id: "3pm-085", groupKey: "3PM", text: "3PM loading… uninstall avoidance now." },
    { id: "3pm-086", groupKey: "3PM", text: "Be advised: 3PM punishes spiritual procrastination." },
    { id: "3pm-087", groupKey: "3PM", text: "Alert: 3PM meetings may cause clarity and discomfort." },
    { id: "3pm-088", groupKey: "3PM", text: "Almost 3PM. Your addiction is writing a comeback speech." },
    { id: "3pm-089", groupKey: "3PM", text: "3PM detected. Please update your emotional software." },
    { id: "3pm-090", groupKey: "3PM", text: "Warning: At 3PM you may experience side effects like truth, humor, and hope." },
    { id: "3pm-091", groupKey: "3PM", text: "3PM alert: The universe expects vulnerability." },
    { id: "3pm-092", groupKey: "3PM", text: "Time-sensitive notice: 3PM ruins relapse plans." },
    { id: "3pm-093", groupKey: "3PM", text: "Warning: At 3PM, accountability becomes contagious." },
    { id: "3pm-094", groupKey: "3PM", text: "3PM is approaching. Bring your humility and a beverage." },
    { id: "3pm-095", groupKey: "3PM", text: "Alert: 3PM disables ‘I’m fine’ mode." },
    { id: "3pm-096", groupKey: "3PM", text: "Warning: At 3PM your secrets start sweating." },
    { id: "3pm-097", groupKey: "3PM", text: "Attention: 3PM has entered the chat." },
    { id: "3pm-098", groupKey: "3PM", text: "Alert: 3PM may cause unexpected self-awareness." },
    { id: "3pm-099", groupKey: "3PM", text: "3PM ahead: Prepare excuses for immediate deletion." },
    { id: "3pm-100", groupKey: "3PM", text: "Warning: Feelings might become sentient at 3PM." },
    { id: "3pm-101", groupKey: "3PM", text: "3PM in 5 minutes. Detach from whatever lie you’re rehearsing." },
    { id: "3pm-102", groupKey: "3PM", text: "Alert: 3PM is incompatible with pretending." },
    { id: "3pm-103", groupKey: "3PM", text: "Warning: 3PM will expose at least one of your coping mechanisms." },
  ],

  generic: [
    { id: "gen-001", groupKey: "generic", text: "You don’t have to be okay to stay clean today." },
    { id: "gen-002", groupKey: "generic", text: "Relapse lives in silence, not in honesty." },
    { id: "gen-003", groupKey: "generic", text: "Recovery is not pretty. It’s consistent." },
    { id: "gen-004", groupKey: "generic", text: "You’re not behind. You’re just not dead yet." },
    { id: "gen-005", groupKey: "generic", text: "Your addiction hates that you’re reading this instead of using." },
    { id: "gen-006", groupKey: "generic", text: "You don’t have to fix your life today. Just don’t burn it down." },
    { id: "gen-007", groupKey: "generic", text: "You’re allowed to be a mess and still show up for your recovery." },
    { id: "gen-008", groupKey: "generic", text: "Feelings are not fatal. Ignoring them gets dangerous, though." },
    { id: "gen-009", groupKey: "generic", text: "You are not starting from zero. You’re starting from experience." },
    { id: "gen-010", groupKey: "generic", text: "You didn’t ruin everything. You just need a meeting and some water." },
    { id: "gen-011", groupKey: "generic", text: "Your worst day clean still beat your best day using." },
    { id: "gen-012", groupKey: "generic", text: "You don’t need to deserve recovery. You just need to keep coming back." },
    { id: "gen-013", groupKey: "generic", text: "Progress in recovery is mostly: didn’t use, logged in, complained honestly." },
    { id: "gen-014", groupKey: "generic", text: "You’re not too broken for recovery. You’re exactly built for it." },
    { id: "gen-015", groupKey: "generic", text: "You’re allowed to rest. Just don’t retire from recovery." },
  ],
};
